name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  test:
    uses: ./.github/workflows/test.yml

  build:
    name: Build check
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup
      - name: Build
        run: pnpm run build
