name: Lint

on:
  workflow_call:

jobs:
  lint:
    name: Linting and formatting check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
      - name: Lint
        run: pnpm run lint
      - name: Format
        run: pnpm run format
