name: Lint

on:
  workflow_call:

jobs:
  lint:
    name: Linting and formatting check
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup
      - name: Lint
        run: pnpm run lint
      - name: Format
        run: pnpm run format
