name: Publish
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        uses: ./.github/workflows/ci.yml@test
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        uses: ./.github/workflows/ci.yml@lint

  publish:
    needs: [test, lint]
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: ./.github/workflows/ci.yml@build
      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          publish: npm run publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
